name: Infra

on:
  push:
    branches:
      - main 
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - run: pip install Frozen-Flask    #instalar en terminal   

      - name: Deploy
        run: python freeze.py